### ISSUE TITLE
How to show on OPM UI a 'count'?

### ISSUE THREAD

**Issue by jremerich** [OPMDG/check_pgactivity#111]
Hi!

I would like to show how many clients have prices generated in my database. To this, I use the follow SQL:
`select count(distinct cd_cliente) qtd from public.dc_preco`

On pgAdmin and console returns correctly, but using the custom_query service don't return the number. On terminal I get this return:
`[root@localhost check_pgactivity-2.0]# ./check_pgactivity -h localhost -p 5432 -d database -s custom_query --query 'select count(distinct cd_cliente) qtd from public.dc_preco' -c 90 -w 80
Argument "(1 registro)" isn't numeric in numeric gt (>) at ./check_pgactivity line 2925.
POSTGRES_CUSTOM_QUERY OK: Custom query ok`

How can I show the number returned of the 'count' clause in a graph on UI?

Tks!

**Comment by rjuju** [comment]
The query used in `custom_query` must return at least 2 fields:
* the first one is a numeric field, and will be compared to the threshold (if provided)
* the second (and possibly all the others) are the perfdata that will be returned

In your example, you should call check_pgactivity like this:

```
./check_pgactivity -h localhost -p 5432 -d database -s custom_query --query 'select count(distinct cd_cliente), count(distinct cd_cliente) AS qtd from public.dc_preco' -c 90 -w 80
```

So the same count is used for the threshold, and the second value is aliased as "qtd" meaning you'll have a `qtd` serie on the UI.

It's not very clear to me why you get this error, but in any case you should get the last release of check_pgactivity (v2.2).

**Comment by frost242** [comment]
Hi,
Without further update on your side, we close this issue.
