### ISSUE TITLE
Password in CLI

### ISSUE THREAD

**Issue by Quentinvarquet** [OPMDG/check_pgactivity#127]
Hello,

Every time i want to use this plugin I have to put the password even with a pgpass file.

Do you know if is it possible to add the password directly in the CLI check_pgactivity with the database, user, ... ?

**Comment by frost242** [comment]
Hello,

There's no way to supply the password directly from the CLI. What is the exact error message that you obtain ? Do you have anything in the log files ?

**Comment by frost242** [comment]
Any update ?

Just to mention that pgpass authentication works flawlessly with check_pgactivity. We use it in production and I tested yesterday to be sure it still works as it should.

**Comment by frost242** [comment]
Without further movement in this issue, we close. The feature is working, you probably have another problem. Feel free to reopen this issue if needed.
