### ISSUE TITLE
Threshold does not seem to work for Hitratio

### ISSUE THREAD

**Issue by maethor** [OPMDG/check_pgactivity#128]
Hi,

I have a strange bug, it seem's I cannot get a warning or a critical:

```
$ sudo -u postgres ./check_pgactivity -h /var/run/postgresql --status-file /tmp/check_pgactivity.data -F nagios -s hit_ratio -w 90% -c 80% --dbexclude=postgres --dbexclude=repmgr --dbexclude='^template'
POSTGRES_HIT_RATIO OK: 1 database(s) checked | mydb=35.05%;90;80
```

I must have missed something, but after one hour looking at everything I still can't find what.

Is it a bug, or did I miss an option?

**Comment by ioguix** [comment]
Hi @maethor,

This has been fixed in the repository and will be part of the next release.

Thank you for your report and your time!

**Comment by maethor** [comment]
Thank you @ioguix :)
