### ISSUE TITLE
last_vacuum should not return critical if there was no write since last vacuum

### ISSUE THREAD

**Issue by maethor** [OPMDG/check_pgactivity#129]
Hi,

When there is no write on a database since the last vacuum, vacuum does not run. Even a manual vacuum full analyse does not run the vacuum. So on a database where there is no write, the last_vacuum probe will always return CRITICAL. Would it be possible to detect this case?

http://grokbase.com/t/postgresql/pgsql-bugs/10asqyzkn2/bug-5722-vacuum-full-does-not-update-last-vacuum-statistics/oldest

Alternatively, it should be possible to run last_vacuum and last_analyse without thresholds, for graphing purposes only.

Thanks.

**Comment by frost242** [comment]
Hi,

We'll address this issue in a later release. Version 2.3 will be released next week and I hope to do another release with this fix soon.

Thanks

**Comment by frost242** [comment]
I've started working on this issue, a first commit is here but the approach is too naive: https://github.com/frost242/check_pgactivity/tree/last_vacuum
I'll sort this out soon.

**Comment by Krysztophe** [comment]
For graphing purpose, it is possible to set the thresholds in the far future (eg `-w '99999d' -c '99999d')` should be enough.

I suppose it is best to let thresholds as mandatory, so they can't be forgotten.

**Comment by ioguix** [comment]
Hi,

PR #272 is waiting for opinions on perfdata. It will be merged for release 2.5 and this issue will be closed if no further discussions happen in the meantime.
