### ISSUE TITLE
Provide a debian package

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#136]
Add everything to build a Debian package : 

- [ ] files to build the package
- [ ] instructions to build the package in docs/dev/releasing.md

**Comment by Krysztophe** [comment]
Intent to package : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901794
My mentor is Christoph Berg

The packaging will be developed on salsa.debian.org
I don't know if this is useful to copy it later into this main repo.

**Comment by Krysztophe** [comment]
See https://salsa.debian.org/Krysztophe-guest/check_pgactivity
It's working and includes the man page (through pod2man).
Waiting for Christoph Berg return.

**Comment by anayrat** [comment]
Hello,

I am interested for debian package. Any news on this issue?

Regards,

**Comment by Krysztophe** [comment]
No return yet. Don't hold your breath, that will have to wait until the end of this summer anyway.
If you really need the package, it's functional, you just have to build it yourself.

**Comment by anayrat** [comment]
I do not need a package, I just think it should be usefull check_pgactivity provided in pgdg repositories.

**Comment by Krysztophe** [comment]
> apt-cache policy check-pgactivity
> check-pgactivity:
>   Installé : (aucun)
>   Candidat : 2.3-1.pgdg18.04+1
>  Table de version :
>      2.3-1.pgdg18.04+1 500
>         500 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages
>         500 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main i386 Packages

We'll see if this goes quickly into Debian itself....

**Comment by anayrat** [comment]
Maybe we should add debian stuff in this repository? Like https://github.com/HypoPG/hypopg/tree/master/debian

Thanks for this!

**Comment by Krysztophe** [comment]
I just did as Christoph Berg told me, and PG maintainers prefer to work in salsa. I'll ask him.

**Comment by Krysztophe** [comment]
Mission accomplished (PGDG and Debian Buster):

https://packages.debian.org/buster/check-pgactivity

```
$ apt-cache  policy check-pgactivity 
check-pgactivity:
  Installé : 2.3-1.pgdg18.04+1
  Candidat : 2.3-1.pgdg18.04+1
 Table de version :
 *** 2.3-1.pgdg18.04+1 500
        500 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages
        500 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main i386 Packages
        100 /var/lib/dpkg/status
```

The watch file raises a warning when we make a release:
https://salsa.debian.org/Krysztophe-guest/check_pgactivity/blob/master/debian/watch
(The repo is still under my name, it may not stay this way).

I'll update the package if we release this week. 

BTW, we have only a few days to make a v11-ready release that could go into Debian Buster before it freezes.

**Comment by ioguix** [comment]
a few days ? How much days ? I was planing to work on the release this week anyway.

**Comment by Krysztophe** [comment]
Buster soft freeze : 2019-02-12
Full freeze : 2019-03-12  https://release.debian.org/buster/freeze_policy.html

**Comment by ioguix** [comment]
OK, so let's try to release this week to give some time to the packager?

**Comment by Krysztophe** [comment]
v 2.4 is in Debian Buster : https://packages.debian.org/buster/check-pgactivity

**Comment by Krysztophe** [comment]
Should have been close months ago.
