### ISSUE TITLE
Service "uptime"

### ISSUE THREAD

**Issue by Krysztophe** [OPMDG/check_pgactivity#139]
This service would return `now()-pg_postmaster_start_time()`. 

I don't know if this would be useful to integrate something based on  `pg_conf_load_time() ;` too

**Comment by ioguix** [comment]
Hi @Krysztophe,

What would be the thresholds for such services? When would you raise a warning or critical alert?

Is it only for graphing purpose?

**Comment by Krysztophe** [comment]
The use would similar to the uptime Nagios probe, mainly for graphs.
Currently, looking at OPM graphs, I can't know for sure if there was a restart/conf reload somewhere. 

Thresholds would be optional, perhaps raising a critical if uptime<15 min, just to have  a mail sent stored somewhere ; and a conf reload would raise a warning.

I'll try to make a first version in the next days, at least as an exercise for me.

**Comment by frost242** [comment]
At first glance, I couldn't find a good use of such service. As we're thinking to move to Grafana to replace the current OPM GUI, this probe will provide us an easy way to add annotations on graphs to show when the database was restarted and when the configuration was reloaded.

So, I'm OK to include this new service. @ioguix do you agree ?

**Comment by frost242** [comment]
PR merged, thanks ! The new service will appear in next release.
