### ISSUE TITLE
No password option

### ISSUE THREAD

**Issue by cmg-george** [OPMDG/check_pgactivity#143]
Not having an option to specify the password makes it unusable.
I can not change the server to accept user without password and i can not use the .pgpass file because i need different passwords for different hosts

**Comment by rjuju** [comment]
Hello,

I'm not sure I follow your issue.  The .pgpass file can define a different passwords for difference host (and/or port, database,user).

**Comment by cmg-george** [comment]
Uhh... yes indeed. However this will not allow me to send hostaddress as parameter from nagios command :|

**Comment by cmg-george** [comment]
Ok...it can be done via .pgpass !
