### ISSUE TITLE
exclude appname from check_longest_query

### ISSUE THREAD

**Issue by pgstef** [OPMDG/check_pgactivity#150]
Currently, there's --exclude to filter out some queries.

To filter out pg_dump (i.e.), we have to --exclude '^COPY'. That's a bit too agressive. 

What about adding a new parameter --appexclude (i.e.) to improve that?

It could then be implemented as well in check_oldest_idlexact (issue #91 ) for harmonisation.

Any advice against this?

**Comment by pgstef** [comment]
--exclude can be used to filter out both query and application_name

**Comment by frost242** [comment]
Issue fixed, thanks a lot for your contribution.
