### ISSUE TITLE
wal_files service does not need superuser privileges since 10

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#153]
We should mention that this service does not need  superuser privileges since 10 thanks to pg_ls_waldir function:
https://github.com/OPMDG/check_pgactivity/blob/b205d4a436ea38e687dfc431042935bbcf348101/check_pgactivity#L7053

**Comment by frost242** [comment]
We already mention that we support the pg_monitor role feature for practically every services, expect btree_bloat and table_bloat which both requires a GRANT on pg_statistic, and temp_files which requires superuser privileges.

But I agree that we should mention somewhere that we support this feature for every services expect the 3 ones above. I think this information must be added in a separate part of the documentation.

**Comment by Krysztophe** [comment]
Included in #171

**Comment by frost242** [comment]
Fixed
