### ISSUE TITLE
Wrong unit for buffers_backend_fsync

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#158]
Hello,

It seems we forgot to multiply by `block_size` for buffers_backend_fsync :

https://github.com/OPMDG/check_pgactivity/blob/6607a7a915612f038074aa55f6bfff4c6c0fb607/check_pgactivity#L2408-L2411

Regards,

**Comment by rjuju** [comment]
If the backend has to do its own fsync() it'll be done for the whole segment, and there's no guarantee that only the buffer the backend wrote was dirty and will get flushed to disk, so we have to keep this metric as a "number of time a fsync were issued".

**Comment by anayrat** [comment]
Oh right! I close it! Thanks!
