### ISSUE TITLE
Wrong max_nb_wal  calculation

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#159]
Hello,

https://github.com/OPMDG/check_pgactivity/blob/6607a7a915612f038074aa55f6bfff4c6c0fb607/check_pgactivity#L7062-L7066

We are adding a wal *size* with a wal *number* :
```
select * from pg_settings where name = 'max_wal_size';
-[ RECORD 1 ]---+----------------------------------------------
name            | max_wal_size
setting         | 5120
unit            | MB
category        | Write-Ahead Log / Checkpoints
short_desc      | Sets the WAL size that triggers a checkpoint.
```
It appears since `checkpoint_segment` was changed to `max_wal_size` in 9.5

Regards,

**Comment by rjuju** [comment]
Nice catch!  AFAICS, this underlying implementation changed in pg10 (9a3215026bd6955e88bd8c20542cfe6acffdb1c8), for 9.6- it was a number of WAL file.

**Comment by frost242** [comment]
Good catch @anayrat, I assigned the issue to you as you told me you're interested in fixing this issue.
