### ISSUE TITLE
Autovacuum can summarize BRIN indexes Since PG 10

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#162]
Hello,

In postgres 10, autovacuum worker can  summarize BRIN indexes:

https://github.com/postgres/postgres/blob/5df0e99bea1c3e5fbffa7fbd0982da88ea149bb6/src/backend/postmaster/autovacuum.c#L3146

See commit : https://github.com/postgres/postgres/commit/7526e10224f0792201e99631567bbe44492bbde4

We should change check_autovacuum : 
https://github.com/OPMDG/check_pgactivity/blob/6607a7a915612f038074aa55f6bfff4c6c0fb607/check_pgactivity#L1753-L1758

Regards,

**Comment by frost242** [comment]
Fixed !
