### ISSUE TITLE
Update XLOG_PAGE_MAGIC for service archive_folder

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#189]
It seems that XLOG_PAGE_MAGIC is out of sync.

**Comment by frost242** [comment]
Fixed in PR #190

**Comment by Krysztophe** [comment]
Reopening for v 12 and 13.

Patch is coming.

We really need a checklist list for major upgrades...

**Comment by rjuju** [comment]
+1, or regression tests :)

**Comment by ioguix** [comment]
> +1, or regression tests :)

Added in my WIP PR #276.

There's a lot we can add to TAP tests related to the release process. Eg., note that I already had some TAP tests checking the copyright year in all files :)
