### ISSUE TITLE
Add PostgreSQL 11 support

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#192]
This issue sums up the different changes introduced in PG11 that will need some work on our side.

- [x] First, issue #152 must be fixed.
- [ ] A new role must be documented : pg_read_server_files. This one fills the gap between pg10 and previous versions.
- ~~Allow access to file system functions to be controlled by GRANT/REVOKE permissions, rather than super-user checks (Stephen Frost)~~
- [x] Add pg_stat_activity.backend_type now shows the type of background worker (Peter Eisentraut)
- [x] Update XLOG_PAGE_MAGIC
- [x] handle wal_segment_size

I hope I have everything. This one is not as problematic as PG10.

**Comment by anayrat** [comment]
FYI wal_segment_size unit has changed:
In PG 10:
```
name            | wal_segment_size
setting         | 2048
unit            | 8kB
```
In PG 11:
```
name            | wal_segment_size
setting         | 16777216
unit            | B
```
We will have to change several queries :(

**Comment by rjuju** [comment]
@anayrat it changed in https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=fc49e24fa69

**Comment by frost242** [comment]
Thanks, added to the list !

**Comment by Krysztophe** [comment]
I've just pushed #196 about wal_segment_size. 

This corrects wal_files and replication_slots. At least archive_folder must be updated too.

**Comment by Krysztophe** [comment]
I've pushed #197 for the minimal rights in v11. It seems that pg_reads_server_files is not very useful. The problems I've found for unprivileged users  are all linked to EXECUTE rights on pg_ls_dir and other functions.

**Comment by frost242** [comment]
Hello,
Regarding the EXECUTE rights, does it also work with in version 10 ? I'm not able to test pg_read_server_files right now, I'll try to take a look at it soon. I hope to merge your PR in the coming days.

**Comment by Krysztophe** [comment]
@frost242 : nope, on v10, you must be superuser to use pg_ls_dir(). I've tried and the error message is explicit.

**Comment by frost242** [comment]
@Krysztophe Ah, I remember now. The pg_ls_dir() C code explicitely checks for a superuser role, in v10 and before !

**Comment by ioguix** [comment]
#152 has been postoned to 2.5

**Comment by frost242** [comment]
@Krysztophe I came back to this today and played with check_temp_file and EXECUTE rights on function used in the query in PostgreSQL 11. I added 3 filters like has_function_privilege('pg_catalog.pg_ls_dir(text)', 'EXECUTE') but I always end up with a permission denied error, wherever I have put the has_function_privilege() calls. Unless you can come to a good solution, I won't add more complex code to handle this. I'm even inclined to let the query err out for PostgreSQL 11 if the user has no grants on the 3 functions used in the query and add documentation about the steps to follow.
Unless you have some good solution, I remove the item « Allow access to file system functions to be controlled by GRANT/REVOKE permissions, rather than super-user checks (Stephen Frost) ».

**Comment by Krysztophe** [comment]
This can be closed, right?
