### ISSUE TITLE
Chr(30)

### ISSUE THREAD

**Issue by Krysztophe** [OPMDG/check_pgactivity#193]
Remenber, @frost242 : we add once chr(30) appearing in pg_stat_activity.queries from one of our beloved customers.

You made a quick patch on the server itself, that I've copied there for memory : https://github.com/Krysztophe/check_pgactivity/commit/b9c8e936e0620817afa3debb809b2ffd6430b299 . The problem was gone, and the patch apparently forgotten.

Would it be useful to make a clean test case and generalize to other versions?

**Comment by rjuju** [comment]
Isn't that a duplicate of #155 ?

**Comment by ioguix** [comment]
indeed
