### ISSUE TITLE
NRPE unable to read plugin outup

### ISSUE THREAD

**Issue by deric** [OPMDG/check_pgactivity#20]
I'm trying to run `check_pgactivitiy` via NRPE
```
Running command: sudo -u postgres /usr/lib/nagios/plugins/check_pgactivity -h /var/run/postgresql/ -s autovacuum
Command completed with return code 1 and output: 
Return Code: 1, Output: NRPE: Unable to read output
```
For some reason NRPE fails to read the output. Could there be problem with flushing stdout? 

`nrpe` daemon runs under `nagios` user, so I've added `sudo -u postgres`. `nagios` should be able to connect to DB without password. 

`/etc/sudoers`:
```
nagios ALL=NOPASSWD:/usr/lib/nagios/plugins/check_pgactivity,/usr/bin/psql
```
Any ideas what could possibly go wrong?

**Comment by rjuju** [comment]
Hello,

Does the command works running manually with nagios user, and did you restart nrpe ?

Maybe also it's the sudo that fails. You should configure your /etc/sudoers with something like

    Defaults:nagios !requiretty

and test again.

Regards.

**Comment by deric** [comment]
Yes,it's `nagios` user. The problem was in sudoers file, I was missing `(ALL)`:
```
nagios ALL=(ALL) NOPASSWD:/usr/lib/nagios/plugins/check_pgactivity
```
