### ISSUE TITLE
Archiver check should not return code 3 "UNKNOWN" on standby

### ISSUE THREAD

**Issue by xals** [OPMDG/check_pgactivity#200]
Hi,

I am using the archiver check indifferently on a primary and on a standby (I don't want to reconfigure my probes if I have to migrate the primary).

Currently, this check is returning code 3 "UNKNOWN" as following:

```sh
# /usr/bin/sudo -u postgres /usr/local/nagios/plugins/check_pgactivity -h /var/run/postgresql --status-file /tmp/check_pgactivity.data -F nagios -s archiver
CHECK_PGACTIVITY UNKNOWN: Query fail !
psql:/tmp/check_pga-xFQPvg30:16: ERROR:  recovery is in progress
HINT:  pg_walfile_name() cannot be executed during recovery.
# echo $?
3
```

I think this check should return 0 "OK" on a standby instead of 3 "UNKNOWN".

**Comment by xals** [comment]
Little precision, the version of PG is 10.5, and I used the last master version of the script.

**Comment by anayrat** [comment]
Right it is a bug, this probe should work either on primary and standby. Since 9.5 Postgres can archive from standby.

**Comment by ioguix** [comment]
Hi,

Could you please check pull request #216 that is supposed to fix this issue?

Thanks,
