### ISSUE TITLE
Allow float instead of integer for commit_ratio thresholds

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#205]
Hi,

I suggest to allow fload for commmit_ratio service. It could be useful for rollback ratio if your rollback_ratio is under 1%.

Regards,

**Comment by ioguix** [comment]
Didn't we discuss this and suggested to have a rollback_num to deal with such cases? I'm not sure what was the conclusion though.

**Comment by anayrat** [comment]
I think it is not enough. For example, during the night, traffic goes down and we have 1 rollback/s with 1000TPS. During the day we have 20KTPS, so 20 rollbacks/s. Both corresponds to 0.1% rollbacks_rate. Which threshold shoud I use we rollback_num?

**Comment by ioguix** [comment]
Mh, indeed. Digging more around, I'm sure we can find scenarios where it requires multiple threshold depending on the time period.

But anyway, moving from integer to float for this does not seems to be a big deal, so go for it :)

**Comment by anayrat** [comment]
> I'm sure we can find scenarios where it requires multiple threshold depending on the time period.
Hum, this should be managed from nagios side?

Are you ok with https://github.com/OPMDG/check_pgactivity/pull/198/commits/39fffced04d98a0e23b5e9760afbcafc38ae39f8 ?

**Comment by ioguix** [comment]
>> I'm sure we can find scenarios where it requires multiple threshold depending on the time period.

> Hum, this should be managed from nagios side?

This is my point, indeed.

> Are you ok with 39fffce ?

I'm fine with it.

**Comment by ioguix** [comment]
This has been merged. Thanks
