### ISSUE TITLE
Add checksum service

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#226]
Since this commit [Track block level checksum failures in pg_stat_database](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=6b9e875f7286d8535bff7955e5aa3602e188e436) we can track checksum failures. I open this issue to think about adding a service to be alerted when checksum failure happens.

Regards

**Comment by rjuju** [comment]
Good idea.  I still hope that we'll get counters on shared relations in v12, let's wait until there's an answer on that point.

**Comment by rjuju** [comment]
Done in https://github.com/OPMDG/check_pgactivity/commit/0e8b516e95e4364470d4e205aebc9fe68bbcfd23
