### ISSUE TITLE
performance data contains Nagios-incompatible NaN values

### ISSUE THREAD

**Issue by basg** [OPMDG/check_pgactivity#227]
We use check_pgactivity with Icinga, and it seems that performance data contains Nagios-incompliant `NaN` values. This results in lots of warnings about invalid performance data.
This became apparent for us while using the `longest_query` service.

Unless there is a more obvious fix for this that we don't know of, a possible solution for this would be to include in the `nagios` and/or `nagios_strict` output format options to replace `NaN` with `U` (according to https://nagios-plugins.org/doc/guidelines.html#AEN200)

>value, min and max in class [-0-9.]. Must all be the same UOM. value may be a literal "U" instead, this would indicate that the actual value couldn't be determined

Unfortunately I do not speak Perl much, so i can't submit a proper patch for this. It would be very nice if this could be fixed, however!

**Comment by rjuju** [comment]
Agreed.  According to the doc you're pointing, we could change NaN to U in nagios_strict mode.  It would however break opm-wh_nagios compatibility.

**Comment by ioguix** [comment]
>  It would however break opm-wh_nagios compatibility.

Does it really matter as opm-wh_nagios does not use nagios_strict mode?

**Comment by rjuju** [comment]
As far as I know nothing prevents anyone from using nagios_strict mode when setting up checks that are aimed for opm-wh_nagios, and I don't see why it wouldn't be supported.  So yes, we should fix that for the nagios/json strict output, *and* fix whatever will break in opm_wh-nagios.

**Comment by ioguix** [comment]
OK. I had a look at `bin/nagios_dispatcher.pl` in opm_wh-nagios and it's quite simple to fix:

~~~diff
diff --git a/bin/nagios_dispatcher.pl b/bin/nagios_dispatcher.pl
index 6bef444..07f0f5c 100755
--- a/bin/nagios_dispatcher.pl
+++ b/bin/nagios_dispatcher.pl
@@ -52,7 +52,7 @@ my $syslog = 0;
 # They do the parsing of the PERFDATA string
 
 my $value                        = qr/[-+]?[\d\.,]+/;
-my $value_re                     = qr/$value(?:e$value)?|NaN/;
+my $value_re                     = qr/(?:$value(?:e$value)?)|NaN|U/;
 my $value_with_negative_infinity = qr/$value_re|~/;
 
 sub parse_perfrecord {
@@ -285,6 +285,8 @@ sub read_file {
             $perfcounter{SERVICEDESC}  = $parsed_line->{SERVICEDESC};
             $perfcounter{SERVICESTATE} = $parsed_line->{SERVICESTATE};
             $perfcounter{LABEL}        = $perfcounterref->{label};
+            $perfcounter{VALUE}        = 'NaN'
+                if $perfcounterref->{value} eq 'U';
 
             # Okay, lets work on the units. We normalize everything
             my ( $basic_uom, $multfactor )
~~~

If you're agree, I can commit this to opm_wh-nagios and move on here.

**Comment by rjuju** [comment]
LGTM, thanks!

**Comment by ioguix** [comment]
done, see: https://github.com/OPMDG/opm-wh_nagios/commit/6390fc8a00c3423b1d4572d4ae1a5f58f6c9664a

**Comment by ioguix** [comment]
See PR #245 for review.

**Comment by rjuju** [comment]
Thanks @basg and @ioguix!
