### ISSUE TITLE
not possible to specify password as command line option

### ISSUE THREAD

**Issue by azet** [OPMDG/check_pgactivity#229]
Hi,

At the moment it's impossible to specify a password for a specific user as a command line option, if a user with password is used an interactive password prompt shows up. Which of course makes this rather unusable with nagios or NRPE. Would someone be willing to add this simple feature? I might have time in the future but am quite short on time in the coming weeks.

```
[root@xxx check_pgactivity-master]# ./check_pgactivity -h localhost -s locks -w 5 -c 10 -U pghero --debug
DEBUG: Hosts: $VAR1 = [
          {
            'db' => 'template1',
            'name' => 'host:localhost port:5432 db:template1',
            'user' => 'pghero',
            'pgversion' => undef,
            'port' => 5432,
            'host' => 'localhost'
          }
        ];
DEBUG: Query: SELECT setting FROM pg_catalog.pg_settings WHERE name IN ('server_version_num', 'server_version') ORDER BY name = 'server_version_num'
DEBUG: Env. host   : localhost
DEBUG: Env. port   : 5432
DEBUG: Env. user   : pghero
DEBUG: Env. db     : template1
Password for user pghero:
```

Thanks!

**Comment by rjuju** [comment]
Hi,

The lack of option to specify a password is on purpose, as we're following the same restriction as postgres' tools to disallow such an option, for security reason.  If you need a password authentication, you can use psql's supported ways to provide it, that is usage of PGPASSWORD environnment variable or a .pgpass file.

That being said, we should definitely add a "-w" to psql options, so we don't interactively ask for a password.

**Comment by ioguix** [comment]
> That being said, we should definitely add a "-w" to psql options, so we don't interactively ask for a password

Go for it

**Comment by rjuju** [comment]
Done in de404d9ca13e282f8328146b55dfe107c472cb2b.

**Comment by ioguix** [comment]
Thanks!

**Comment by azet** [comment]
Thanks for the fast and accurate information!
