### ISSUE TITLE
Bug in the temp_files report

### ISSUE THREAD

**Issue by gleu** [OPMDG/check_pgactivity#23]
On a 9.1.1 server, it gives me this error message:

ERROR:  set-valued function called in context that cannot accept a set

I tried on a 9.1.15, and it works for me. I don't think this is an issue with the minor releases. It might be well to look further into it.

**Comment by rjuju** [comment]
Hello Guillaume,

I tried to reproduce this issue with a fresh 9.1.1 cluster, but I didn't get any luck to reproduce it.

As far as I know, this is the typical error returned by C SRF functions if they don't accept returning a tuplestore. I can't think of a reason to raise this error when calling any of pg_stat_file, pg_ls_dir or generate_series in a psql connection.

I guess the server has something really specific. Is this issue happening on every check ?

**Comment by gleu** [comment]
Yeah, it did. Though I don't see it again. Could just be me. I'm closing the ticket, but I'll get back if I have more news :)
