### ISSUE TITLE
v12: remove walsenders from max_connections in check_backends

### ISSUE THREAD

**Issue by ioguix** [OPMDG/check_pgactivity#232]
From release notes:
> Have max_wal_senders not count as part of max_connections (Alexander Kukushkin)

**Comment by Krysztophe** [comment]
What does it change for us? We currently show the number of connections (client backend+bg workers) for each database, including a pseudo-database called 'replication' (number of lines from pg_database). We compare the total (`num_backends`) to max_connections - superuser_reserved_connections.

If I understand correctly, that simply means that we must not count this 'replication' database in `num_backends` from v12.
