### ISSUE TITLE
unable to define "dbservice" to monitor stream replication

### ISSUE THREAD

**Issue by sahubharat25** [OPMDG/check_pgactivity#233]
Hi  Guys,

I am using the check_pgactivity plugin in my Nagios to monitor PostgreSQL-10 stream replication. I was checking the document and didn't find any relevant details related  **dbservice**.  Can you please let me know how to I can define **dbservice** .  I went through the README document and find out that there is a pg_service.conf can be used and please let me know how I can use that.

**Comment by rjuju** [comment]
Hi,

Indeed the documentation states:

```
-S, --dbservice SERVICE_NAME

    The connection service name from pg_service.conf to use.

    See section CONNECTIONS for more informations.
```

You can see more information about that file in postgres documentation at https://www.postgresql.org/docs/current/libpq-pgservice.html.

Let us know if you need any further help.

**Comment by ioguix** [comment]
I added the link to the manpage. I close this long opened issue with no other activity.
