### ISSUE TITLE
Optional Password parameter option 

### ISSUE THREAD

**Issue by sahubharat25** [OPMDG/check_pgactivity#234]
Hi Guys,
If possible can you please add an optional password parameter option in the check_pgactivity nagios plugins.

**Comment by rjuju** [comment]
Hello, this has already been asked multiple times, and we don't support it on purpose.  See for instance https://github.com/OPMDG/check_pgactivity/pull/33 and https://github.com/OPMDG/check_pgactivity/issues/229 for more details about the rationale.

**Comment by unix196** [comment]
I think that it would be appropriate to indicate in Documentation about this decision

**Comment by rjuju** [comment]
@unix196 that seems like a good idea.  Do you want to submit a PR?

**Comment by unix196** [comment]
Ok) a little later, when I implement your plugin

**Comment by Krysztophe** [comment]
@unix196 : See #234, is it okay for you?

**Comment by unix196** [comment]
Yes, it's looks nice
