### ISSUE TITLE
last_vacuum/analyze : raise an error if last_... & last_auto... are both NULL

### ISSUE THREAD

**Issue by Krysztophe** [OPMDG/check_pgactivity#235]
The service does not return an error when some tables have last_${type}  last_auto${type} both at NULL.

I have a database where the autovacuum analyze may be stuck for days (there is a bug in the function of a functional index) and it leads to null values in these fields. But any other table with valid values hide this and the database-wide last_analyze is okay. This is the only way I can think of to detect this problem through check_pgactivity. 

I don't see why last_${type} and last_auto${type} may both be NULL, except after a crash or table creation, and this should not last long.

**Comment by Krysztophe** [comment]
Probably solved by #249 / #256

**Comment by ioguix** [comment]
Hi,

I'm not sure to understand the original problem. To be honest, I did not invest a lot of time on it yet. But, as it seems you are able to reproduce the problem on your side...may I ask you to check if #249 / #256 actually fixed your issue?

Many thanks,

**Comment by Krysztophe** [comment]
I can't reproduce, this seems solved. Case closed.
