### ISSUE TITLE
Backends service: graph max_connections

### ISSUE THREAD

**Issue by gleu** [OPMDG/check_pgactivity#24]
I'd like to graph the max_connections value. Would it be possible to add the max_connections value as another "database"?

This should do it:

diff --git a/check_pgactivity b/check_pgactivity
index 14bdadb..2781c40 100755
--- a/check_pgactivity
+++ b/check_pgactivity
@@ -1164,6 +1164,9 @@ sub check_backends {
         FROM pg_stat_database AS s
             JOIN pg_database d ON d.oid=s.datid
         WHERE d.datallowconn
+               UNION
+               SELECT 'max_connections', current_setting('max_connections')::integer,
+                   current_setting('max_connections')
     };
 
     # warning and critical are mandatory.
@@ -1196,7 +1199,7 @@ sub check_backends {
         if $args{'warning'} =~ /^([0-9.]+)%$/;
 
     LOOP_DB: foreach my $db (@rs) {
-        $num_backends += $db->[1];
+        $num_backends += $db->[1] if $db->[0] !~ '^max_connections$';
         push @perfdata,
             "$db->[0]=$db->[1];$args{'warning'};$args{'critical'};0;$db->[2]";
     }

Quick-n-dirty patch, you're warned :)

**Comment by rjuju** [comment]
+1 for adding the info.

Actually, we already gather the max_connections settings (in order to compute the threshold), so there's no need to add an UNION ALL clause (it's available as $rs[0][2] for instance).

Speaking of the max_connections value, I think it'd be more useful to retrieve the number of allowed connections for a regular user, not a superuser which mean substracting the superuser_reserved_connections value. What do you think ?

**Comment by gleu** [comment]
You're right about the not-needed UNION ALL. A quick fix would be to add the information from $rs[0][2].

The issue about superuser vs standard user connections is interesting, though it isn't trivial. You can also set connection limit on users and databases. Do you really want to go that far?

**Comment by rjuju** [comment]
I think that jte superuser_reserved_connections parameter is pretty much a standard, so we should rely on its value. If your application connects as a superuser, you'll have alerts a little bit sooner, but I think it won't be the worst issue you'll get.

Setting up limit on user and/or database should stay in the specific DBA knowledge, and therefore not enforced in this probe. And I think it's easily doable with the custom_query if needed.

**Comment by gleu** [comment]
Agreed.
