### ISSUE TITLE
Annoying dependency to JSON::PP

### ISSUE THREAD

**Issue by yhuelf** [OPMDG/check_pgactivity#253]
Commit 752aea91 adds a dependency to JSON::PP, but this Perl module isn't always installed by default on database servers.

Would it be possible to dynamically import this module at runtime only when JSON output is used?

**Comment by rjuju** [comment]
@yhuelf could you try with latest master and confirm that @frost242 patch is fixing the problem for you?

**Comment by yhuelf** [comment]
Thanks! It works well :-)

**Comment by frost242** [comment]
Thanks for the report.
