### ISSUE TITLE
PostgreSQL 13: changes in pg_replication_slots

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#260]
PostgreSQL 13 introduced some changes in replication slots handling and in the pg_replication_slots view.

First, a new parameter max_slot_wal_keep_size appeared to limit the retention of a replication slot. The slot may become invalid and content is deleted if this limit is reached. This limit has to be taken in account in check replication_slots.

Second, the pg_replication_slots sees two new columns : wal_status shows the status of the WAL files inside the slot. When the column shows "lost", the slot has a problem. The other column is safe_wal_size which tells if the slot will or not reach its limit soon, as per parameter max_slot_wal_keep_size.

For reference, Álvaro Herrera wrote an article summarizing the changes in PG13 : https://www.2ndquadrant.com/en/blog/pg13-slot-size-limit/

**Comment by ioguix** [comment]
I just created a PR to close this issue.

Could you please do some review/tests?

Thanks!
