### ISSUE TITLE
2.5 Release: with or without PG13?

### ISSUE THREAD

**Issue by Krysztophe** [OPMDG/check_pgactivity#262]
The last release is 19 months away, not even officially PG12 compatible. That's a long time for people that only want officially released software.

Can we plan something for the near future?

**Option 1**:  A release ASAP with these PR that need a last polish or just an answer:

#186
#256
#261 
#248 ?

**Option 2**: A release with all of this + some PG13 improvements, such as:

 #260 

Feelings?

**Comment by frost242** [comment]
If you can afford to spend some time to release right now, please do it. I don't have time to work on #260 myself right now.

**Comment by Krysztophe** [comment]
I can release but I'd like to see at least the bugs, incompatibilities or small items committed.
#267 and #263  are waiting, too.

Would it be possible to take an hour together in the next days to decide what to release?

**Comment by ioguix** [comment]
I did some quick housekeeping.

Here is the checklist:

  * [ ] #186
  * [ ] #248
  * [ ] #256
  * [ ] #260
  * [ ] #261
  * [ ] #263
  * [ ] #267

**Comment by ioguix** [comment]
done
