### ISSUE TITLE
Lack of maintenance on temp table

### ISSUE THREAD

**Issue by ioguix** [OPMDG/check_pgactivity#279]
Following discussions on #249.

Large and long-living temp tables lacking vacuum/analyze can impact production. On the opposite, small and/or short-living temp tables are mostly on the low risk side.

We decided to ignore temp tables altogether in 2.5 and postpone the discussion to 2.6.

What to do with them?

* check them by default?
* add a switch to include them in the check? eg. `--with-temp-table`? 
* add a switch to only check temp tables? eg. `--temp-table-only`?
* support --include/--exclude?

The later is useful on its own and deserve to be added in 2.6 anyway. But it might not be enough to include/exclude temp tables to the check anyway.

Thoughts? other ideas?

**Comment by Krysztophe** [comment]
Maintenance vacuum will never take care of temp tables, and the goal of the service is to check that periodic maintenance works. 

A ''--with-temp-table'' is easy enough to add, though.

''--exclude'' is a must, I have a customer with many work tables in a separate schema.

Perhaps add ''--ignore-unlogged'' too, as they are often unimportant work tables?

**Comment by Krysztophe** [comment]
Another idea : get rid of tables below some size threshold , where vacuum and analyze will probably not matter. That would get rid of a few useless positives.

**Comment by Krysztophe** [comment]
We definitely need ''--exclude''.

I have a customer with an active DB, but he needs only to supervise ''public'', the other schemas are static, work tables, or not important, or technical (postgis schemas...).

**Comment by yhuelf** [comment]
We could also get rid of tables for which the ratio **n_live_tup / n_mod_since_analyze** is less than 10 (or some other threshold) for the ANALYZE check.

And consider the ratio **n_live_tup / n_dead_tup** for the VACUUM check ?

**Comment by ioguix** [comment]
Temp tables are supposed to be handled by application creating them to vacuum/analyze them.

If something should really take care of this, this should be outside of the last_vacuum/last_analyze service, in eg. a temp table related service. But I'm really doubtful we want this is a monitoring tool aim to check if an instance is behaving correctly. Frontend software issues are not really our problem. 

This service spirit is to check if periodic global maintenance succeed eg. during the night... And now, this is documented since PR #366.

Closing this.
