### ISSUE TITLE
File «${storage}» not recognized as a check_pgactivity status file.

### ISSUE THREAD

**Issue by aaujon** [OPMDG/check_pgactivity#287]
Hi,

I'm using nagios to check a postgres DB.
Sometime /var/local/pgactivity/pgactivity.data become empty (0byte) which forbid any future calls to be executed until I delete this file.
I guess there is a race condition somewhere.

I'm not sure it fixes my issue but in save method : The exclusive lock should be acquired before lock_retrieve line 567 and released after lock_store line 571. I think with the current code 2 processes can  read the file at the same moment and the last one will override the first one write.

The problem occurs everyweek or so, I can provide more information if you need.

Thanks,

**Comment by aaujon** [comment]
Hi,

I finally got the trace that show this issue, that's a race condition between processes.

It show that running at the same time /usr/lib/nagios/plugins/check_pgactivity -s commit_ratio AND /usr/lib/nagios/plugins/check_pgactivity -s hit_ratio leads to a forever running process (couldn't strace it, I will do it next time) and all the new execution using the statusfile are KO (status file is empty)

Logs comes from nagios-nrpe-plugins
`august 02 03:25:47 HOST nrpe[26101]: Connection from X.X.X.1 port 56987
august 02 03:25:47 HOST nrpe[26101]: Host X.X.X.1 is asking for command 'check_pg_commit_ratio' to be run...
august 02 03:25:47 HOST nrpe[26101]: Running command: /usr/lib/nagios/plugins/check_pgactivity -d postgres -U POSTGRESQL_USER --status-file /var/local/pgactivity/pgactivity.data -s
 commit_ratio
august 02 03:25:47 HOST nrpe[26116]: CONN_CHECK_PEER: checking if host is allowed: X.X.X.1 port 29852
august 02 03:25:47 HOST nrpe[26116]: Connection from X.X.X.1 port 29852
august 02 03:25:47 HOST nrpe[26116]: Host X.X.X.1 is asking for command 'check_pg_hit_ratio' to be run...
august 02 03:25:47 HOST nrpe[26116]: Running command: /usr/lib/nagios/plugins/check_pgactivity -d postgres -U POSTGRESQL_USER --status-file /var/local/pgactivity/pgactivity.data -s
 hit_ratio

august 02 03:26:08 HOST nrpe[26116]: Command completed with return code 0 and output: POSTGRES_HIT_RATIO OK: 22 database(s) checked
august 02 03:26:08 HOST nrpe[26116]: Return Code: 0, Output: POSTGRES_HIT_RATIO OK: 22 database(s) checked | 
august 02 03:26:08 HOST nrpe[26116]: Connection from X.X.X.1 closed.

august 02 03:27:35 HOST nrpe[26234]: Connection from X.X.X.1 port 52401
august 02 03:27:35 HOST nrpe[26234]: Host X.X.X.1 is asking for command 'check_pg_bgwriter' to be run...
august 02 03:27:35 HOST nrpe[26234]: Running command: /usr/lib/nagios/plugins/check_pgactivity -d postgres -U POSTGRESQL_USER --status-file /var/local/pgactivity/pgactivity.data -s bgwriter
august 02 03:27:35 HOST nrpe[26234]: Command completed with return code 3 and output:
august 02 03:27:35 HOST nrpe[26234]: Return Code: 3, Output: NRPE: Unable to read output
august 02 03:27:35 HOST nrpe[26234]: Connection from X.X.X.1 closed.
`

**Comment by rjuju** [comment]
Hi @aaujon 

Sorry for the lack of response, and thanks a lot for keeping looking into it.

I agree that the status file concurrency handling isn't good.  I see an attempt to make `is_storable()` safe using a shared flock(), but it looks like the various save(), load()... functions never had a proper exclusive flock() to make that work.

So yes we have a guarantee that we'll read or write something consistent, but clearly does not ensure that:something else won't write to the file in between (so the next write might discard those), and it doesn't guarantee anything at all for is_storable().

I think we should just get rid of the shared flock in is_storable() and protect the whole content of save() and similar function with a shared lock when only reading the status file and exclusive lock when writing to it, and thus get rid of the `lock_*` storable variants.

@ioguix any objection?

**Comment by ioguix** [comment]
Sorry guys, the notifs about this discussion were buried on my side for so long time :/

@rjuju: our `save()` and `load()` functions are using `lock_store` and `lock_retrieve` from module Storable.  `lock_store` takes an exclusive lock before writing and `lock_retrieve` takes a shared one before reading. So theoretically, we are on the safe side.

However, according to Storable documentation, it uses `flock()` internally that might not be supported on all system, neither on NFS. @aaujon, could you confirm you are not in this situation?

**Comment by rjuju** [comment]
@ioguix as I said I agree that using `lock_store` and `lock_retrieve` should be enough to ensure seeing something consistent but **NOT** to avoid losing data.

Unless I'm missing something it's possible that 2 concurrent calls to check_pgactivity read the same file content, modify the hash locally and sequentially write the modified hash, the 2nd write overwriting the 1st one.

So again, our approach is bad and we should protect the whole save/load function rather than some operations inside.

**Comment by ioguix** [comment]
@rjuju, sorry, I didn't understand this while reading your previous message.

I understand the race condition now, but I'm not sure how it could end up with an empty status file. Moreover, note that the race condition you describe exists, but is quite narrow as the `save()` function is doing:

1. re-read full hash with shared lock
2. replace **only** the on-going check data in hash: `$all->{$hostkey}{$name} = $ref;`
3. write the full hash with exclusive lock

In my understanding, the race condition you describe exists there, in the `save()` call __only__, but not during the whole save/load function calls, or does it?

So, as far as my understanding is correct, the solution might be to exclusive flock the status file during the whole `save()` call, protecting both the `retrieve()` and `store()` calls under the same lock umbrella.

Another brutal solution would be to exclusive flock the status file during the whole check_pga execution as soon as we read the file for the first time, but I'm afraid this might hurt the concurrency quite a bit under some conditions.

**Comment by aaujon** [comment]
Hi @ioguix @rjuju 
Thanks for your time!
I'm not using NFS filesystem, the problem has been well described by @rjuju .
I believe that protecting the retrieve() and store() under an exclusive lock will fix this. No need to do more as it will effectively hurt performances.
