### ISSUE TITLE
Some counters are in a weird unit

### ISSUE THREAD

**Issue by marco44** [OPMDG/check_pgactivity#29]
For instance, pg_stat_bgwriter:

Perfdata contains the difference from the pg_stat_bgwriter counters since last execution. 

This has no meaning for the user: you never know the exact duration between 2 executions. If you have a downtime, then you'll have a spike at next connection.

A more rigourous measure would be difference divided by time. You'd get consistent results no matter if there is 10s or 20 minutes between calls. Anyway, the unit would seem logical: buffers allocations per minute for instance. Currently, it is just "buffers". It's like mixing distance and speed...

**Comment by rjuju** [comment]
+1 for having Bps values.

FWIW, the counters are already translated from blocks to bytes.

**Comment by ioguix** [comment]
After auditing the code, it seams only one service need a fix: bgwriter

The service "temp_files" also report the number of temp files produced since last run, leading to a big spike if the check is broken for some time, but it reports as well a file/s ratio.

I am now working on fixing bgwriter.
