### ISSUE TITLE
last_analyze and last_vacuum are generating too many false positives

### ISSUE THREAD

**Issue by yhuelf** [OPMDG/check_pgactivity#294]
Maybe we should ignore tables for which last_analyze is NULL AND last_autoanalyze is NULL, for the sake of simplicity.

**Comment by Krysztophe** [comment]
So, you would miss tables that are never analyzed due to some problems... 

Could be a parameter, though.

**Comment by yhuelf** [comment]
Yes, we would, this is not ideal.

**Comment by ioguix** [comment]
The point of this check is to detect table that were never analyzed. So $subject is in contradiction with the goal itself.

However, we might want to support `--exclude` to filter out some known exception tables.

**Comment by yhuelf** [comment]
I agree with you, my suggestion doesn't really make sense. As I only reviewed the SQL query (and not the Perl code), I'm unsure about why we have false positives.
