### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#297]
Hello!

Latest release was on November. Since then, there is a bug fix on last_vacuum / last_analyze https://github.com/OPMDG/check_pgactivity/commit/e700cd90aa99cdeaaa85583bc8787a7d2ebda367

It may be worth to release a new version with this fix?

Thanks

**Comment by frost242** [comment]
+1, good idea

I've just spotted a bug that does not happen on a vanilla Postgres, will fix it however.

**Comment by FelixSchwarz** [comment]
release early, release often so +1 for me.

@ioguix: Anything in particular which blocks a new release? At least it would contain some fixes :-)

**Comment by Krysztophe** [comment]
+1

**Comment by ioguix** [comment]
I would like to finish the PR #303 first. Then we can do a release.

**Comment by anayrat** [comment]
2.6 has been released on 2022-07-08.
Thanks!
