### ISSUE TITLE
check_archiver is broken with a PostgreSQL flavour imitating Oracle's behaviour with empty/NULL strings

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#298]
Hello,

I've noticed that at least check_archiver is broken when using a PostgreSQL flavour that mimics Oracle's non-standard behaviour with string handling.
The fix is written but I wonder if we are willing to maintain such fix ? At the moment, I didn't stumble on other possible issues, but I didn't make lot of tests for now.

What do you think about this issue ?

Kind regards

**Comment by Krysztophe** [comment]
If  this is useful , not too big, documented, why not?

If not, at least document that it does not work with this PG flavor and we don't care.

**Comment by frost242** [comment]
The patch consists of some CASE WHEN column IS NOT NULL THEN ... ELSE NULL END in the query. Quite easy, but the query needs some additional comments, to avoid some future "optimizations" that will break it again.

**Comment by rjuju** [comment]
What exactly is the problem and where?  Wouldn't a coalesce be a better answer than a case/when?

But generally, I'm assuming that such a version of postgres would basically break every single tool written for a normal version of postgres, so they should provide a way to get the spec-compliant behavior, maybe at the db or user level?

**Comment by frost242** [comment]
I don't have access to this environment anymore. I'll get back on it if we install this flavor again.
