### ISSUE TITLE
Detecting "vertical" fragmentation

### ISSUE THREAD

**Issue by gleu** [OPMDG/check_pgactivity#30]
When someone drops a column in a table, the table is not rewritten. VACUUM won't claim the space. And check_pgactivity won't detect the space used for nothing. Wouldn't it be right that check_pgactivity checks that kind of issues?

**Comment by rjuju** [comment]
Sorry for late answer.

I think a VACUUM FULL does claim the space, but keep the dropped attributes. I don't really see how we could distinguish the two cases.

**Comment by ioguix** [comment]
Hi,

It seems the `table_bloat` service already detect the bloat related to dropped columns:

~~~
$ cat << EOQ | psql test
> create table test as select i, md5(i::text) from generate_series(1,1000000)i;
> alter table test drop column md5;
> vacuum analyze test;
> EOQ

$ perl -l check_pgactivity -s table_bloat --dbinclude test -w 40% -c 60% 
POSTGRES_TABLE_BLOAT WARNING: 1/19 table(s) bloated | 'table bloated in test'=1
test.public.test 30.688MB/65.112MB (47.11%);

$ vacuumdb -f -t test test

$ perl -l check_pgactivity -s table_bloat --dbinclude test -w 40% -c 60% 
POSTGRES_TABLE_BLOAT OK: Table bloat ok | 'table bloated in test'=0
~~~

Cheers @gleu,

**Comment by gleu** [comment]
Great. I don't know what I've done to think it didn't work.
