### ISSUE TITLE
Check for floating point typed columns

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#315]
Hello,

Would it be welcome to have a new service to check for floating point typed columns ?

I had the bad pleasure to detect some float8 columns to handle financial datas. Would it be interesting at some point to provide such service ? Otherwise, I can handle this in a custom query.

Thanks for your feedback.
Thomas

**Comment by Krysztophe** [comment]
Slippery slope. There are many things of this kind to detect. That will end with a service called "audit_schema" that will always detect some things. A worthy goal and that would be fun to do, but maybe not in this project?

**Comment by frost242** [comment]
You are right, it's a bad idea as there are so many common mistakes to detect.

Thanks, closing this issue.
