### ISSUE TITLE
Performance data not following plugin specification

### ISSUE THREAD

**Issue by flopma** [OPMDG/check_pgactivity#34]
Hello,

Thank you for this useful plugin we are currently putting in place with Icinga to monitor our Postgres DBs.

While setting up the monitoring; I found out that commit_ratio gives performance data which contains units like 'tps'. Unfortunately Icinga is unable to process this because it follows the Nagios plugin guidelines.

https://nagios-plugins.org/doc/guidelines.html
http://docs.icinga.org/latest/en/perfdata.html

which does not describe tps as a performance data unit.

Could you take a look into this please ?

```
--- check_pgactivity.orig	2016-03-16 17:47:57.933416750 +0100
+++ check_pgactivity	2016-03-16 17:49:29.766926601 +0100
@@ -2443,9 +2443,9 @@
         $global_commits   += $commits;
         $global_rollbacks += $rollbacks;
 
-        push @perfdata, sprintf "'%s_commit_rate'=%.2ftps",   $db, $commit_rate;
-        push @perfdata, sprintf "'%s_rollback_rate'=%.2ftps", $db, $rollback_rate;
-        push @perfdata, sprintf "'%s_xact_rate'=%.2ftps",     $db, $xact_rate;
+        push @perfdata, sprintf "'%s_commit_rate'=%.2f",   $db, $commit_rate;
+        push @perfdata, sprintf "'%s_rollback_rate'=%.2f", $db, $rollback_rate;
+        push @perfdata, sprintf "'%s_xact_rate'=%.2f",     $db, $xact_rate;
 
         if ( $rollbacks == 0) {
             $ratio = 0;
@@ -2464,7 +2464,7 @@
                     next THRESHOLD_LOOP;
                 }
                 if ( $val eq "rollback_rate" and $crit{$val} < $rollback_rate ) {
-                    push @msg_crit => sprintf "'%s'=%.2ftps", $prefix, $rollback_rate;
+                    push @msg_crit => sprintf "'%s'=%.2f", $prefix, $rollback_rate;
                     next THRESHOLD_LOOP;
                 }
                 if ( $val eq "rollback_ratio" and $crit{$val} < $ratio ) {
@@ -2479,7 +2479,7 @@
                     next THRESHOLD_LOOP;
                 }
                 if ( $val eq "rollback_rate" and $warn{$val} < $rollback_rate ) {
-                    push @msg_warn => sprintf("'%s'=%.2ftps", $prefix, $rollback_rate );
+                    push @msg_warn => sprintf("'%s'=%.2f", $prefix, $rollback_rate );
                     next THRESHOLD_LOOP;
                 }
                 if ( $val eq "rollback_ratio" and $warn{$val} < $ratio ) {
```

**Comment by rjuju** [comment]
That's unfortunate :(

The opm UI does a big use of the units to split the metrics and display with a nice formatting.

The commit_ratio isn't the only service that'll break icinga. How about a new option that force the check_pgactivity's perfdata to respect the standard UOM, in order to keep current behavior when possible?

**Comment by flopma** [comment]
You're the boss ;-) But I am not a Perl guy so I am not sure I can do this (the new option). Thank you

**Comment by rjuju** [comment]
:)

I added a new branch named output_strict, with a commit which add a --strict option to check_pgactivity. If this flag is provided, only the legacy units (B, s, % and c) will be used. See https://github.com/OPMDG/check_pgactivity/commit/5ca48155a6c5b0bc3fedfec4eaca0904edd029d5

Can you try and tell me if it works for you ? ( https://raw.githubusercontent.com/OPMDG/check_pgactivity/output_strict/check_pgactivity ) I may have missed some units.

@ioguix : would you be ok with this new option? I also fixed a bug in this commit for temp_files service, the same perfdata keys were used multiple times, see https://github.com/OPMDG/check_pgactivity/blob/master/check_pgactivity#L5511

**Comment by flopma** [comment]
Yes this works -with the --strict parameter. Thank you very much

**Comment by ioguix** [comment]
Hello,

Just for your information, this will be implemented in a different way in the next version of check_pgactivity. A new argument `--format` appears with different output format available. The one you are interested in is `nagios_strict`. 

This is currently available in branch v2 of this repository.
