### ISSUE TITLE
stat_snapshot_age and pg15+

### ISSUE THREAD

**Issue by blogh** [OPMDG/check_pgactivity#352]
On PostgreSQL 15, stat_snapshot_age fails with :

```
CHECK_PGACTIVITY UNKNOWN: Could not parse query result!
```

"pg_stat_get_snapshot_timestamp()" returns NULL.
```
postgres=# SELECT extract(epoch from (now() - pg_stat_get_snapshot_timestamp())) AS age;
 age 
-----
    
(1 ligne)

postgres=# SELECT now(), pg_stat_get_snapshot_timestamp();
              now              | pg_stat_get_snapshot_timestamp 
-------------------------------+--------------------------------
 2023-05-23 17:18:35.952784+02 | 
(1 ligne)
```

Given the changes on the activity stats in pg15, the service is probably meaningless for these versions.

Maybe we should document this or give a more meaningful message in pg15+.

**Comment by blogh** [comment]
Note:  The fonction displays something only when stats_fetch_consistency is "snapshot". (if I read the [code](https://github.com/postgres/postgres/blob/5df5bea29070b420452bdb257c3dec1cf0419fca/src/backend/utils/activity/pgstat.c#L897) correctly.

You then have to start a transaction and query some stats.

```
[local]:5437 postgres@postgres=# set stats_fetch_consistency to snapshot;;
SET

[local]:5437 postgres@postgres=# BEGIN;
BEGIN
[local]:5437 postgres@postgres=#* SELECT * FROM pg_stat_bgwriter \gx
-[ RECORD 1 ]---------+------------------------------
checkpoints_timed     | 358
checkpoints_req       | 1
checkpoint_write_time | 1181038
checkpoint_sync_time  | 359
buffers_checkpoint    | 19181
buffers_clean         | 0
maxwritten_clean      | 0
buffers_backend       | 51456
buffers_backend_fsync | 0
buffers_alloc         | 57553
stats_reset           | 2023-05-22 11:46:30.801103+02

[local]:5437 postgres@postgres=#* SELECT pg_stat_get_snapshot_timestamp();
 pg_stat_get_snapshot_timestamp 
--------------------------------
 2023-05-23 17:38:33.153357+02
(1 row)
```

**Comment by frost242** [comment]
Hello,

This check aimed to detect a staled stats collector that happened sometimes before release 15. As you noted, this service is now useless.
+1 for documenting and add a code path to exit properly when PostgreSQL 15 is detected.
-1 for hacking something by changing stats_fetch_consistency.

Could you send a PR ?

Thanks

**Comment by blogh** [comment]
Hi,

I wasn't proposing to hack something with `stats_fetch_consistency`. It would be dumb because we would 
be checking the age of the snapshot we just created. Sorry if my second note caused any confusion.

I can look into this, I am clueless about perl so It might take some time.

**Comment by frost242** [comment]
Hi,

Ok, everything is fine then. Take a look or update the issue here, I'll take care of this as soon as I find some free time. I have other issues to handle.

Kind regards

**Comment by blogh** [comment]
The bounds seem to work

Current version : 
<pre>
[benoit@benoit-dalibo check_pgactivity]$ pg env pgsql-15
Switching to version pgsql-15
postgres (PostgreSQL) 15.3

[benoit@benoit-dalibo check_pgactivity]$ ./check_pgactivity --service stat_snapshot_age
CHECK_PGACTIVITY UNKNOWN: Could not parse query result!
</pre>

New version :
<pre>
[benoit@benoit-dalibo check_pgactivity]$ pg env pgsql-9.4
Keeping version: postgres (PostgreSQL) 9.4.26, using pgsql-9.4

[benoit@benoit-dalibo check_pgactivity]$ ./check_pgactivity --service stat_snapshot_age
Service stat_snapshot_age is not compatible with host 'binary defaults port:5441 db:postgres' (v9.4.26).

[benoit@benoit-dalibo check_pgactivity]$ pg env pgsql-9.5
Keeping version: postgres (PostgreSQL) 9.5.24, using pgsql-9.5


[benoit@benoit-dalibo check_pgactivity]$ ./check_pgactivity --service stat_snapshot_age
POSTGRES_STAT_SNAPSHOT_AGE OK | statistics_age=-0.008688

[benoit@benoit-dalibo check_pgactivity]$ pg env pgsql-14
Switching to version pgsql-14
postgres (PostgreSQL) 14.8

[benoit@benoit-dalibo check_pgactivity]$ ./check_pgactivity --service stat_snapshot_age
POSTGRES_STAT_SNAPSHOT_AGE OK | statistic

[benoit@benoit-dalibo check_pgactivity]$ pg env pgsql-15
Switching to version pgsql-15
postgres (PostgreSQL) 15.3

[benoit@benoit-dalibo check_pgactivity]$ ./check_pgactivity --service stat_snapshot_age
Service stat_snapshot_age is not compatible with host 'binary defaults port:5437 db:postgres' (v15.3).
</pre>

pod2text & pod2select seem to generate what I wanted.

**Comment by frost242** [comment]
Thank you @blogh !
