### ISSUE TITLE
Some service return code of 13

### ISSUE THREAD

**Issue by yuhuman** [OPMDG/check_pgactivity#37]
Thanks for OPM, I now can monitor some services of my database, I added locks, btree_bloat and backends days ago, and it seems quite fine. However when I add the service using command like `check_pgactivity -h localhost -p 5432 -s last_vacuum -w 30m -c 1h30m` into the nagios service define file, the nagios returns code of 13 is out of bounds, any other command parameters need to be configured? And the service database_size return the same code of 13.

Thanks a lot.

**Comment by rjuju** [comment]
Hello,

Thanks!

In the nagios UI, you should have more informations in the `Status Information` field for these services. What are they showing?

If there's no relevant information, can you try to execute this command line as the nagios user, and see the output? You can also add the --debug option to get more information.

**Comment by yuhuman** [comment]
Yes, it return that "can't write into ./check_pgactivity.data: Permission denied at ./check_pgactivity line 463."
I changed the permission of the folder, and then the services of database_size and last_vacuum work fine.
Thanks !
