### ISSUE TITLE
First execution of pg_dump_backups causes an error

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#39]
Hi,

When pg_dump_backups is run for the first time, the following erreur appears :
Remote command execution failed: Use of uninitialized value in subtraction (-) at /home/dalibo/bin/check_pgactivity line 4493.

This error should be silented.

**Comment by yuhuman** [comment]
HI, if there is a warning like "perl warning: setting locale failed", I thinks the link is helpful for you.
http://ubuntuforums.org/showthread.php?t=1346581

**Comment by ioguix** [comment]
@yuhuman : I'm not sure to understand how related to the topic it is.

@frost242 : fixed in commit 1785596b7b2e144b348e723ec143f25691f9a139

**Comment by frost242** [comment]
Thanks !
