### ISSUE TITLE
how to show custom_query on the OPM UI?

### ISSUE THREAD

**Issue by yuhuman** [OPMDG/check_pgactivity#45]
Hello,

Thanks for OPM. 

I want to show some query on the OPM UI like the current connection-number of each user. I used the `--custom_query` service and there appeared the information of the connections on the Nagios UI, and I want to show them on OPM UI, what should I do?

Thanks.

**Comment by rjuju** [comment]
Hello,

Any service returning perfdata should be displayed on OPM UI. Does your query configured in this service returns perfdata? The first field in the custom query is used as a return code, and every other field is used for perfdata, see http://opm.readthedocs.io/probes/check_pgactivity.html:

> All other columns will be used to generate the perfdata. The query must display them in the perfdata format, with unit if required (eg. “size=35B”). If a field contains multiple values, they must be separated by a space.

If this part is ok, maybe you declared multiple services using custom-query with the same name in nagios. In this case, OPM will only display one graph, the service name being the identifier of the service.

**Comment by yuhuman** [comment]
Hi @rjuju ,

I am still confused about the custom query service, could you please make me a example about the SQL query of ` select count,usename.* from (select usename, count(usename) from pg_stat_activity group by usename` or any others ? 

Thanks very much!

**Comment by rjuju** [comment]
Per documentation on http://opm.readthedocs.io/probes/check_pgactivity.html#services

> The first column will be used to perform the test for the status if warning and critical are provided.
> [...]
> All other columns will be used to generate the perfdata. The query must display them in the perfdata format, with unit if required (eg. “size=35B”). If a field contains multiple values, they must be separated by a space.

This kind of query can be tricky to write, since you need to obtain results in only one row.

This query should work
```sql
WITH s AS (
    SELECT usename, count(*) as nb
    FROM pg_stat_activity
    GROUP BY usename
)
SELECT sum(nb), string_agg(usename || '=' || nb, ' ') AS val
FROM s;
```

**Comment by rjuju** [comment]
Hello, did this query solve your issue?
