### ISSUE TITLE
Wrong unit in check_bgwriter service

### ISSUE THREAD

**Issue by rjuju** [OPMDG/check_pgactivity#46]
Counters ``buffers_backend`` and ``buffers_backend_fsync`` should be in Bps instead of Nps.

**Comment by ioguix** [comment]
Agree for `buffers_backend`, not `buffers_backend_fsync` which is the number of time a fsync has been issued by a backend, not a volume of data.

**Comment by rjuju** [comment]
Indeed, I looked to fast on this issue. Fixed in d50c49f
