### ISSUE TITLE
Support version 10 and more

### ISSUE THREAD

**Issue by ioguix** [OPMDG/check_pgactivity#48]
PostgreSQL will change its numbering policy starting with the next release 10, dropping the major release on 2 digit to keep it on a single number.

To keep it backward compatible with the old policy, the pg_version_num will stay compatible with its old behavior.

check_pgactivity does not rely on pg_version_num because it appears in 8.2, so it recompute it based on the "human" format. The current code will likely break with the new version scheme.

We should fix it to use pg_version_num first and fallback on the current implementation if pg_version_num fail.

**Comment by frost242** [comment]
Change done in 1546acbf30dce827b9597bee31008961ab5907fb and 490a4b519ae4c9be215b6af7655b3e7dc10f12c8.

I think you can close this issue.

**Comment by ioguix** [comment]
Thank you Thomas!
