### ISSUE TITLE
permission denied for relation pg_statistic on Amazon RDS

### ISSUE THREAD

**Issue by davidedg** [OPMDG/check_pgactivity#50]
On Amazon RDS, pg_statistic is owned by rdsadmin role, so many checks fail with permission denied error.

The tables [pg_stats](https://www.postgresql.org/docs/9.3/static/view-pg-stats.html) should be used instead.

I think  https://github.com/ioguix/pgsql-bloat-estimation has updated query, but if this is not the case, then please Bucardo postgres nagios plugin [here](https://github.com/bucardo/check_postgres/blob/master/check_postgres.pl#L3811), which I can confirm it works with Amazon RDS.

Thank you.

**Comment by frost242** [comment]
Hi,

Older versions of check_pgactivity used pg_stats to calculate bloat. However we had performance issues on databases containing a very large number of tables. So we had to use pg_statistic instead.

However, your monitoring role requires superuser privileges with check_pgactivity. This has always been required.
To solve this issue, can you add your monitoring role to the rdsadmin role ?

Regards

**Comment by davidedg** [comment]
You cannot add any role to rdsadmin role - afail it's Amazon reserved.
There are other tools that can read without being superuser - namely
https://pganalyze.com/docs/install/amazon_rds/02_create_monitoring_user
Hope this can help to improve the program (I'm a noobie in postgres itself
so I can't understant if this will be actually useful ;D )



2016-11-17 15:19 GMT+01:00 Thomas <notifications@github.com>:

**Comment by frost242** [comment]
Hello,

Sorry for getting back to you so late. In the same period, I used to build an extension that provides workarounds for monitoring PostgreSQL with a non-superuser role. It's provided as is and is not tested against Amazon RDS. Feel free to adapt it to your needs.

However, please note that version 2.3 of check_pgactivity will provide full compatibility with PostgreSQL 10, and permits monitoring using the pg_monitor role.

I'll close this issue. Feel free to reopen it if you need further informations.
