### ISSUE TITLE
Handle wait events correctly for 9.6+

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#54]
Commit edc4cf8 introduced some basic support for wait events in 9.6. However, it only handles strong locks but not the Buffer Pin waits and the 2 LWLocks waits. We should think about how we treat them.

Commit edc4cf8 simply handles strong locks as queries waiting for locks, which is the "historical" behavior of the waiting column of pg_stat_activity from older versions of PostgreSQL.

**Comment by ioguix** [comment]
Moreover, we should probably review all other queries related to pg_stat_activity as its schema changed.

**Comment by frost242** [comment]
Pull Request #82 gives more informations about wait events.

Also, check_backends_status is the only probe that uses the column waiting/wait_event_type in the query. Other probes don't use this ones.

**Comment by frost242** [comment]
I close this issue as it makes no sense to get deeper in wait events handling in check_pgactivity.
