### ISSUE TITLE
Password parameter for connection test

### ISSUE THREAD

**Issue by Karthik427** [OPMDG/check_pgactivity#56]
Hi,

Please help me in passing password as a parameter to the connection service test. 
---------------------------------
/usr/local/nagios/libexec/check_pgactivity-2.0 # ./check_pgactivity -s connection -h x.x.x.x -p 1111
Password:
-------------------------------

Thanks.

**Comment by rjuju** [comment]
Hello,

The best way to solve your issue is to configure a **.pgpass** file in the home directory of the user performing this check.  You can follow [the official documentation](https://www.postgresql.org/docs/current/static/libpq-pgpass.html) for more information on how to do.

**Comment by rjuju** [comment]
Hello, could you solve your issue?
