### ISSUE TITLE
 File «/usr/lib64/nagios/plugins/check_pgactivity.data» not recognized as a check_pgactivity status file.

### ISSUE THREAD

**Issue by SysEng101** [OPMDG/check_pgactivity#58]
I am using check_pgactivity with Icinga2 instead of Nagios and am getting the _"File «/usr/lib64/nagios/plugins/check_pgactivity.data» not recognized as a check_pgactivity status file."_ errors on every call to check_pgactivity (for all services using check_pgactivity), and then 1 minute later the call to check_pg_activity works fine. This pattern repeats on every subsequent call.

Here is an example from Icinga2:

![image](https://cloud.githubusercontent.com/assets/9611096/22260328/ded183ca-e236-11e6-8e7c-a484ca957542.png)

Could this be a race condition for all the services competing for read access to the same status file?

Any assistance would be greatly appreciated,

Thanks.

**Comment by ioguix** [comment]
Hello,

We suppose there might have a concurrency problem between the `is_storable` and the `save` sub.

What is your version of perl?

**Comment by ioguix** [comment]
Could you please try if the following patch fix your issue?

```diff
diff --git a/check_pgactivity b/check_pgactivity
index 17e202c..191e617 100755
--- a/check_pgactivity
+++ b/check_pgactivity
@@ -36,6 +36,7 @@ use Getopt::Long qw(:config bundling no_ignore_case_always);
 use List::Util qw(max);
 use Pod::Usage;
 use Scalar::Util qw(looks_like_number);
+use Fcntl qw(:flock);
 use Storable qw(lock_store lock_retrieve);
 
 use Config;
@@ -453,10 +454,14 @@ sub is_storable($) {
     my $storage = shift;
     my $head;
 
-    return Storable::file_magic( $storage ) if
-        defined *Storable::file_magic{CODE};
-
     open my $fh, '<', $storage;
+    flock($fh, LOCK_SH) or die "can't get shared lock on $storage: $!";
+
+    if ( defined *Storable::file_magic{CODE} ) {
+        close $fh; # release the shared lock
+        return Storable::file_magic( $storage );
+    }
+
     read $fh, $head, 64;
     close $fh;
 
```

**Comment by ioguix** [comment]
Erf, sorry, I left a small race condition in there by closing the filehandle before calling file_magic. Here is a better patch:

~~~diff
diff --git a/check_pgactivity b/check_pgactivity
index 17e202c..025eaa4 100755
--- a/check_pgactivity
+++ b/check_pgactivity
@@ -36,6 +36,7 @@ use Getopt::Long qw(:config bundling no_ignore_case_always);
 use List::Util qw(max);
 use Pod::Usage;
 use Scalar::Util qw(looks_like_number);
+use Fcntl qw(:flock);
 use Storable qw(lock_store lock_retrieve);
 
 use Config;
@@ -453,10 +454,16 @@ sub is_storable($) {
     my $storage = shift;
     my $head;
 
-    return Storable::file_magic( $storage ) if
-        defined *Storable::file_magic{CODE};
-
     open my $fh, '<', $storage;
+    flock($fh, LOCK_SH) or die "can't get shared lock on $storage: $!";
+
+    if ( defined *Storable::file_magic{CODE}
+         and Storable::file_magic( $storage )
+    ) {
+        close $fh; # release the shared lock
+        return 1;
+    }
+
     read $fh, $head, 64;
     close $fh;
 
~~~

**Comment by SysEng101** [comment]
I've implemented the patch and have been monitoring the logs, and so far no errors! It looks like the patch resolved the issue. Thank you very much!

**Comment by ioguix** [comment]
This has been pushed in the main repository. The fix will be in the next release.

Thank you for the bug report and feeback!
