### ISSUE TITLE
Filter out some applications

### ISSUE THREAD

**Issue by gleu** [OPMDG/check_pgactivity#91]
Some tools take a looong time to execute, and they held a transaction as long as they run. Yeah, pg_dump is my target :) I shouldn't get an alert if pg_dump holds a transaction for a long time. It looks like this:

```
 03:39:12.951715 | pg_dump          | 14555 | COPY public.<bip> (<bip>) TO stdout;
 03:39:12.95212  | pg_dump          | 14554 | COPY <bip>.<bip> (<bip>) TO stdout;
 03:39:12.952371 | pg_dump          | 14552 | COPY <bip>.<bip> (<bip>) TO stdout;
 03:39:12.952425 | pg_dump          | 14550 | COPY <bip>.<bip> (<bip>) TO stdout;
```
Probably it should filter out pg_dump connection lines (something like "WHERE application_name='pg_dump' ").

Thanks.

**Comment by gleu** [comment]
This patch should do the trick:

```
diff --git a/check_pgactivity b/check_pgactivity
index 6663cc8..fd21e2c 100755
--- a/check_pgactivity
+++ b/check_pgactivity
@@ -4706,7 +4706,7 @@ sub check_oldest_2pc {
 
 =item B<oldest_idlexact> (8.3+)
 
-Check the oldest I<idle> transaction.
+Check the oldest I<idle> transaction. Above 9.2, it filters out pg_dump and pg_dumpall connections.
 
 Perfdata contains the max/avg age and the number of idle transactions
 per databases.
@@ -4744,6 +4744,7 @@ sub check_oldest_idlexact {
                 ), -1)
             FROM pg_database AS d
             LEFT JOIN pg_stat_activity AS a ON (a.datid = d.oid AND state='idle in transaction')
+            WHERE a.application_name NOT IN ('pg_dump', 'pg_dumpall')
         }
     );
 
```

**Comment by frost242** [comment]
Hi,
Thinking about it, maybe we could add an option to filter out specific applications ?

**Comment by gleu** [comment]
That would be a nice step forward.

**Comment by ioguix** [comment]
Yes, I bet on allowing the user to use something like `--exclude` to define what to exclude.

**Comment by frost242** [comment]
We already have --dbexclude as a common pattern. Maybe we could add --appexclude ?

**Comment by ioguix** [comment]
We already support the `--exclude` argument in our Getopt conf, and we already use it in the same kind of purpose. -1 to create a new argument.

**Comment by frost242** [comment]
Thanks Stefan for adding this feature !
