### ISSUE TITLE
Default host

### ISSUE THREAD

**Issue by tobixen** [OPMDG/check_pgactivity#92]
I want  to be able to use `/usr/local/lib/monitoring/plugins/check_pgactivity -s $service` without any connection parameters - and it should initiate psql without connection parameters.

The default behaviour for psql is to connect through the unix socket file, found at the compile-time configured default socket directory (/tmp in the official postgres release, but /var/run/postgres under most distributions) and then connect as the logged-in-user (I'll add an nrpe user with superuser privileges, alternatively just do `sudo -u postgres`).

Two things:

* It's required to add either at least one connection parameter.  This is just an aesthetic issue, I just don't want to pass a "dummy" connection parameter.

* The default host is "localhost".  This causes a TCP connection, and the user is no longer authenticated by the OS, so one is asked for a password:

    $ sudo -u postgres psql -h localhost
    Password: 
    psql: fe_sendauth: no password supplied

Possibly this could be solved by running up an ident server, but I don't want to go that route.

I could add '--host /tmp' or '--host /var/run/postgres', but I don't like to do such hard-coding as it may be distro-specific where the socket file is located.

I could add some config service file on the host with a password ... but I don't want to complicate the setup.

Last, `-h ""` seems to work, but it does give some warnings so perhaps best to avoid it:

    $ sudo -u postgres /usr/local/lib/monitoring/plugins/check_pgactivity -h '' -s autovacuum
    Use of uninitialized value in sprintf at /usr/local/lib/monitoring/plugins/check_pgactivity line 879.
    POSTGRES_AUTOVACUUM OK: Number of autovacuum: 0 | ANALYZE=0 VACUUM=0 VACUUM_FREEZE=0 VACUUM_ANALYZE=0 oldest_autovacuum=NaNs max_workers=3

I'm considering writing up a pull request on this one.

**Comment by maethor** [comment]
@tobixen you can use `-h /var/run/postgresql` without other user and password params.

**Comment by tobixen** [comment]
> @tobixen you can use `-h /var/run/postgresql` without other user and password params.

Ref the research I did in march 2017, even though /var/run/postgresql is the correct answer in most distributions, the default directory in the official postgresql release is (or, was at that time) /tmp.

I don't want to hard code /var/run/postgresql into my manifests as it can be fragile.

**Comment by ioguix** [comment]
Fixed in #213, thank you!
