### ISSUE TITLE
Add oldest_waiting service

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#95]
Currently, we have no way to determine if some transaction is blocked for a certain period of time.

A service oldest_waiting seems like a good idea.

**Comment by tobixen** [comment]
I also want to monitor this.

The perf data is already available in backends_status - it should be trivial to add threshold levels for the max age of each status here.

**Comment by tobixen** [comment]
using https://github.com/tobixen/check_pgactivity/blob/master/check_pgactivity it's possible to do like this:

    check_pgactivity -s backends_status -w active=20s -c active=600s

and it will yield a warning if some query has been running for more than 20s.

not very well tested I must admit.

**Comment by frost242** [comment]
Hi, thanks for the PR, I'll look through it later, I have no time right now.

**Comment by frost242** [comment]
Change done in commit 9e10b450bde76a99ad3fd9e9cdb5f321c5a606c0. Thanks to Tobias Brox for his initial patch.
