### ISSUE TITLE
database_size is a confusing service

### ISSUE THREAD

**Issue by tobixen** [OPMDG/check_pgactivity#98]
The thresholds sent to database_size is applied on the database growth since last query - this may be slightly unexpected from the name of the service.

Further, the perf-data gives the absolute database size and not the growth.  I was staring at the numbers for a while and believing I found a bug - until I read the documentation.  I think it's not appropriate that the thresholds apply to one variable while the actual reported data is another variable.  And I even do have a use-case where I'd actually like to monitor the absolute database size.

Suggestion: mark database_size as deprecated and split it into two, database_size_growth as a rename of the currenct database_size (but it should return growth values in perfdata), and database_total_size, database_disk_size or something like that for a service that checks for and returns the actual database size.  Check the available disk space on the postgres data partition (if possible) and let percentages in the thresholds apply to the ratio database_size / (database_size + free disk space)

**Comment by ioguix** [comment]
Hi,

I agree this service is quite confusing.

Unfortunately, checking the available disk space on the postgres data partition is not possible in a clean or portable way. Moreover, checking the available space/partition size is not related to a PostgreSQL tool, but a system tool that should be deployed as well anyway (eg. check_disk :)).

I'm fine with the idea to rename database_size as database_size_delta (the db can growth...or shrink :)) and create a new service database_size which apply on actual absolute db size.

**Comment by tobixen** [comment]
Right, on second thought the "ratio of database size towards database size plus free disk space" probably doesn't make much sense anyway.  I would like to use a percentage there rather than fixed size though.  Ratio of database size versus size of all databases could probably work, though in many settings it's always close to 100%.  Well, I guess this is yet another threshold variable that has to be hand tuned, where it's meaningless to try to pick some default fire-and-forget value :-)

**Comment by Krysztophe** [comment]
+1 for adding a check on the database full size

I propose to allow something like ` -w "1%,100GB" -c "2%,150GB"` to keep the compatibility with the current behaviour and get an alarm when getting (slowly) above some threshold ?

**Comment by ioguix** [comment]
I'm ok with @Krysztophe proposal. Not with the syntax. Currently, a raw number, a percentage, or a
size are all accepted as size variation. So it is not clear if a size apply to the total size or variation. Same for percentage or raw number.

Myabe we should pick something like `-w "delta=1%,size=100GB" -c "delta=10GB,size=150GB"`. `size` would only allow a size or a raw number.

Plus, we should probably add a perfdata about the size variation of each database.

Extending the current database_size avoid some code duplication and to break compatibility with existing setup.

**Comment by ioguix** [comment]
I need reviewers on PR #225.

**Comment by ioguix** [comment]
Done!
Thanks,
